#!/bin/bash
wget --recursive --wait=0.25 --no-clobber --page-requisites --adjust-extension --span-hosts --convert-links --restrict-file-names=windows --user-agent=Mozilla -e robots=off  --domains $2 --no-parent $1

